FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine

RUN \
  apk add --no-cache \
    python \
    py-pip \
    groff \
    less \
    git \
    zip \
    findutils \
    coreutils \
    && \
  apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
    bash \
    && \
  pip install --upgrade \
    awscli && \
  dotnet tool install --version 3.2.0 --tool-path /usr/local/bin Amazon.Lambda.Tools && \
  chmod +x /usr/local/bin/dotnet-lambda